version: '3.9'

services:
  backend:
    image: 'securecapita:latest'
    build: .
    container_name: backend
    env_file:
      .env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    depends_on:
      - liquibase
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://database:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}",
        "spring.datasource.username" : "${MYSQLDB_USER}",
        "spring.datasource.password" : "${MYSQLDB_ROOT_PASSWORD}",            
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.properties.hibernate.globally_quoted_identifiers" : "true",
        "spring.jpa.properties.hibernate.format_sql" : "true",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.show-sql" : "true",
        "spring.jpa.generate-ddl" : "true",
        "spring.jpa.database-platform" : "org.hibernate.dialect.MySQL8InnoDBDialect",
        "spring.sql.init.mode" : "never",
        "spring.liquibase.change-log" : "classpath:config/liquibase/master.xml"
      }'
  database:
    image: 'mysql:latest'
    container_name: database
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    volumes:
      - "./src/main/resources/database/init_database.sql:/docker-entrypoint-initdb.d/init_database.sql"
    environment:
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
  liquibase:
    build: ./liquibase
    container_name: liquibase
    depends_on:
      - database
    volumes:
      - ./liquibase/master.xml:/liquibase/master.xml
      - ./liquibase/changelog:/liquibase/changelog
    command: "--username=${MYSQLDB_USER} --password=${MYSQLDB_ROOT_PASSWORD} --url=jdbc:mysql://database:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE} --changeLogFile=master.xml --log-level=INFO update"