CREATE TABLE IF NOT EXISTS UserEvents(
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    device VARCHAR(100) DEFAULT NULL,
    ip_address VARCHAR(100) DEFAULT NULL,
    created_ad DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY userevents_ibfk_1 (user_id) REFERENCES Users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY userevents_ibfk_2 (event_id) REFERENCES Events(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    PRIMARY KEY(id)
);